/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_saxonica_functions_extfn_PhpCall */

#ifndef _Included_com_saxonica_functions_extfn_PhpCall
#define _Included_com_saxonica_functions_extfn_PhpCall
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
